---
- name: Update package lists
  ansible.builtin.apt:
    update_cache: yes

- name: Install prerequisites for Docker
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
    state: present

- name: Create directory for Docker GPG key
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"

- name: Download Docker GPG key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: "0644"

- name: Add Docker repository if not already present
  shell: |
    if ! grep -q "download.docker.com" /etc/apt/sources.list.d/docker.list; then
      echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" > /etc/apt/sources.list.d/docker.list
    fi
  args:
    executable: /bin/bash

- name: Update package lists after adding Docker repo
  ansible.builtin.apt:
    update_cache: yes

- name: Install Docker CE
  ansible.builtin.apt:
    name: docker-ce
    state: present
