---
- name: Install Zsh package
  ansible.builtin.package:
    name: zsh
    state: present
  become: true # This uses sudo to install the package

- name: Check if Oh My Zsh is already installed
  ansible.builtin.stat:
    path: "/home/{{ ansible_user }}/.oh-my-zsh"
  register: oh_my_zsh_installed

- name: Download Oh My Zsh installer
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: /tmp/omz-install.sh
    mode: '0755'
  when: not oh_my_zsh_installed.stat.exists

- name: Install Oh My Zsh manually
  ansible.builtin.shell: |
    cd /home/{{ ansible_user }}
    git clone https://github.com/ohmyzsh/ohmyzsh.git .oh-my-zsh
    cp .oh-my-zsh/templates/zshrc.zsh-template .zshrc
  args:
    creates: "/home/{{ ansible_user }}/.oh-my-zsh"
  when: not oh_my_zsh_installed.stat.exists

- name: Clone zsh-autosuggestions plugin
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: "/home/{{ ansible_user }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
    version: "master"  # Or better, use a specific tag for stability
    update: false

- name: Clone zsh-syntax-highlighting plugin
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "/home/{{ ansible_user }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
    version: "master"  # Or better, use a specific tag for stability
    update: false

- name: Create .zshrc with plugins
  ansible.builtin.copy:
    dest: "/home/{{ ansible_user }}/.zshrc"
    mode: '0644'
    content: |
      export ZSH="/home/{{ ansible_user }}/.oh-my-zsh"
      ZSH_THEME="agnoster"
      plugins=(git z zsh-autosuggestions zsh-syntax-highlighting)
      source $ZSH/oh-my-zsh.sh

      # History settings
      HISTFILE=/home/{{ ansible_user }}/.zsh_history
      HISTSIZE=10000
      SAVEHIST=10000

      # Aliases
      alias ll="ls -lah"
      alias gs="git status"

      # Editor
      export EDITOR=vim

      # Enable auto-completion
      autoload -U compinit
      compinit

      # Add custom paths
      export PATH="/home/{{ ansible_user }}/bin:/usr/local/bin:$PATH"

- name: Set Zsh as default shell
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    shell: /bin/zsh
  become: true
