---
- name: Create main runner directory
  ansible.builtin.file:
    path: "{{ base_directory }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"

- name: Download GitHub runner
  ansible.builtin.get_url:
    url: "https://github.com/actions/runner/releases/download/v{{ github_runner_version }}/actions-runner-linux-{{ runner_architecture }}-{{ github_runner_version }}.tar.gz"
    dest: "{{ base_directory }}/actions-runner-linux-{{ runner_architecture }}-{{ github_runner_version }}.tar.gz"
    checksum: "sha256:{{ github_runner_hash }}"
    mode: "0644"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Extract GitHub runner binaries
  ansible.builtin.unarchive:
    src: "{{ base_directory }}/actions-runner-linux-{{ runner_architecture }}-{{ github_runner_version }}.tar.gz"
    dest: "{{ base_directory }}"
    remote_src: true
    creates: "{{ base_directory }}/run.sh"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Remove GitHub runner tar.gz file
  ansible.builtin.file:
    path: "{{ base_directory }}/actions-runner-linux-{{ runner_architecture }}-{{ github_runner_version }}.tar.gz"
    state: absent
